name: Dev Image Cleanup

on:
  schedule:
    - cron: '5 0 * * *' # every day at 00:05 UTC
    
jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old dev images
    steps:
      - uses: snok/container-retention-policy@d3bdcf5ce9b05f685154e4a16c39233b245e3d53 # v3.1.0
        with:
          account: ghostmaintainers
          token: ${{ secrets.IMG_RETENTION }}
          image-names: tubeless-dev
          keep-n-most-recent: 3
          cut-off: 7d
          dry-run: false
